In [1]:
import pandas as pd
import time
from systems.forecasting import TradingRule, Rules
from systems.provided.rules.ewmac import ewmac_forecast_with_defaults as ewmac
from sysdata.config.configdata import Config
from systems.forecast_combine import ForecastCombine
from systems.basesystem import System
from systems.accounts.accounts_stage import Account
from systems.forecast_scale_cap import ForecastScaleCap
from systems.rawdata import RawData
from systems.positionsizing import PositionSizing
from sysdata.sim.csv_futures_sim_data import csvFuturesSimData

# my_account = Account()
# scale_and_cap = ForecastScaleCap()
# combiner = ForecastCombine()
# raw_data = RawData()
# position_size = PositionSizing()
# data = csvFuturesSimData()

# instruments
portfolio_intruments =  [
     "NASDAQ",
     "SP500",
     "US10",
     "RUSSELL",
     "EUR",
     "GOLD",
     "SILVER",
     "EUROSTX",
     "BITCOIN",
     "CRUDE_W_mini",
     "LIVECOW"
     ]

test_instrument_code = "NASDAQ"
main_rule_name = "ewmac_32_128"

# define rules
ewmac_5_20 = TradingRule((ewmac, [], dict(Lfast=5, Lslow=20)))
ewmac_20_60 = TradingRule((ewmac, [], dict(Lfast=20, Lslow=60)))
ewmac_32_128 = TradingRule((ewmac, [], dict(Lfast=32, Lslow=128)))
ewmac_60_150 = TradingRule((ewmac, [], dict(Lfast=60, Lslow=150)))
ewmac_100_200 = TradingRule((ewmac, [], dict(Lfast=100, Lslow=200)))

system_rules = Rules(dict(ewmac_5_20=ewmac_5_20, 
                      ewmac_20_60=ewmac_20_60,
                      ewmac_32_128=ewmac_32_128,
                      ewmac_60_150=ewmac_60_150,
                      ewmac_100_200=ewmac_100_200))

Configuring sim logging

In [2]:
# Forecast scalar (fixed)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-scalar-fixed

def test_forecast_scalar_fixed():
    config = Config()
    config.use_forecast_scale_estimates = False
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    system = System([scale_and_cap, system_rules], data, config)
    
    raw_forecasts = system_rules.get_raw_forecast(test_instrument_code, "ewmac_32_128") #system.rules.get_raw_forecast(test_instrument_code, "ewmac_32_128")
    scalar = scale_and_cap.get_forecast_scalar(test_instrument_code, "ewmac_32_128")
    scaled_forecasts = scale_and_cap.get_scaled_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    
    return pd.DataFrame({
        'raw': raw_forecasts,
        'scalar': scalar,
        'scaled': scaled_forecasts,
        'capped': capped_forecasts
    })

test_forecast_scalar_fixed()

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-27 18:36:28 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-27 18:36:28 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-27 18:36:28 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-27 18:36:28 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-27 18:36:28 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128

                 raw  scalar    scaled    capped
index
1999-12-14       NaN     1.0       NaN       NaN
1999-12-15       NaN     1.0       NaN       NaN
1999-12-16       NaN     1.0       NaN       NaN
1999-12-17       NaN     1.0       NaN       NaN
1999-12-20       NaN     1.0       NaN       NaN
...              ...     ...       ...       ...
2024-03-22  6.218251     1.0  6.218251  6.218251
2024-03-25  6.373547     1.0  6.373547  6.373547
2024-03-26  6.489081     1.0  6.489081  6.489081
2024-03-27  6.655521     1.0  6.655521  6.655521
2024-03-28  6.777110     1.0  6.777110  6.777110

[6338 rows x 4 columns]

In [3]:
# Forecast scalar (fixed)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-scalar-fixed

def test_forecast_scalar_fixed_per_rule():
    config = Config()
    config.use_forecast_scale_estimates = False
    config.forecast_scalars=dict(ewmac_32_128=3)
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    system = System([scale_and_cap, system_rules], data, config)
    
    raw_forecasts = system_rules.get_raw_forecast(test_instrument_code, "ewmac_32_128") #system.rules.get_raw_forecast(test_instrument_code, "ewmac_32_128")
    scalar = scale_and_cap.get_forecast_scalar(test_instrument_code, "ewmac_32_128")
    scaled_forecasts = scale_and_cap.get_scaled_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    
    return pd.DataFrame({
        'raw': raw_forecasts,
        'scalar': scalar,
        'scaled': scaled_forecasts,
        'capped': capped_forecasts
    })

test_forecast_scalar_fixed_per_rule()

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-27 18:36:29 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-27 18:36:29 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-27 18:36:29 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-27 18:36:29 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-27 18:36:29 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128

                 raw  scalar     scaled     capped
index
1999-12-14       NaN       3        NaN        NaN
1999-12-15       NaN       3        NaN        NaN
1999-12-16       NaN       3        NaN        NaN
1999-12-17       NaN       3        NaN        NaN
1999-12-20       NaN       3        NaN        NaN
...              ...     ...        ...        ...
2024-03-22  6.218251       3  18.654752  18.654752
2024-03-25  6.373547       3  19.120641  19.120641
2024-03-26  6.489081       3  19.467243  19.467243
2024-03-27  6.655521       3  19.966564  19.966564
2024-03-28  6.777110       3  20.331329  20.000000

[6338 rows x 4 columns]

In [4]:
# Forecast scalar (estimated)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-scalar-estimated

# Nota: per qualche motivo il risultato in c# è leggermente diverso da quello di pysystemtrade a causa di questa funzione:
# avg_abs_value = x.rolling(window=window, min_periods=min_periods).mean()

# L'input di questa funzione sembra corrispondere, a parte per alcuni NaN iniziali che in c# sono già stati rimossi
# Credo sia dovuto all'approssimazione ma non sono convinto.

def test_forecast_scalar_estimated():
    config = Config()
    config.use_forecast_scale_estimates=True
    config.forecast_scalar_estimate=dict(pool_instruments=False, func="sysquant.estimators.forecast_scalar.forecast_scalar", window=250000, min_periods=500, backfill=True)
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    system = System([scale_and_cap, system_rules], data, config)
    
    raw_forecasts = system_rules.get_raw_forecast(test_instrument_code, "ewmac_32_128") #system.rules.get_raw_forecast(test_instrument_code, "ewmac_32_128")
    scalar = scale_and_cap.get_forecast_scalar(test_instrument_code, "ewmac_32_128")
    scaled_forecasts = scale_and_cap.get_scaled_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    
    return pd.DataFrame({
        'raw': raw_forecasts,
        'scalar': scalar,
        'scaled': scaled_forecasts,
        'capped': capped_forecasts
    })

start = time.perf_counter()
df_pooling = test_forecast_scalar_estimated()
elapsed = time.perf_counter() - start
print(f"Loaded in: {elapsed}")
df_pooling

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-27 18:36:29 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-27 18:36:29 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-27 18:36:29 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-27 18:36:29 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128

2025-12-27 18:36:29 DEBUG base_system {'stage': 'forecastScaleCap'} Getting cross sectional forecasts for scalar calculation for ewmac_32_128 over NASDAQ
2025-12-27 18:36:29 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128
Loaded in: 0.2453220000024885

                 raw    scalar     scaled     capped
index
1999-12-14       NaN  2.927797        NaN        NaN
1999-12-15       NaN  2.927797        NaN        NaN
1999-12-16       NaN  2.927797        NaN        NaN
1999-12-17       NaN  2.927797        NaN        NaN
1999-12-20       NaN  2.927797        NaN        NaN
...              ...       ...        ...        ...
2024-03-22  6.218251  2.743148  17.057581  17.057581
2024-03-25  6.373547  2.742823  17.481513  17.481513
2024-03-26  6.489081  2.742485  17.796208  17.796208
2024-03-27  6.655521  2.742127  18.250286  18.250286
2024-03-28  6.777110  2.741755  18.581176  18.581176

[6338 rows x 4 columns]

In [5]:
# Forecast scalar (estimated with pooling)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-scalar-estimated

# Nota: per qualche motivo il risultato in c# è leggermente diverso da quello di pysystemtrade a causa di questa funzione:
# avg_abs_value = x.rolling(window=window, min_periods=min_periods).mean()

# L'input di questa funzione sembra corrispondere, a parte per alcuni NaN iniziali che in c# sono già stati rimossi
# Credo sia dovuto all'approssimazione ma non sono convinto.

def test_forecast_scalar_estimated_with_pooling():
    config = Config()
    config.instruments = portfolio_intruments
    config.use_forecast_scale_estimates=True
    config.forecast_scalar_estimate=dict(pool_instruments=True, func="sysquant.estimators.forecast_scalar.forecast_scalar", window=250000, min_periods=500, backfill=True)
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    system = System([scale_and_cap, system_rules], data, config)
    
    price = data.daily_prices(test_instrument_code)
    price = price.resample("1B").last()

    raw_forecasts = system_rules.get_raw_forecast(test_instrument_code, "ewmac_32_128") #system.rules.get_raw_forecast(test_instrument_code, "ewmac_32_128")
    scalar = scale_and_cap.get_forecast_scalar(test_instrument_code, "ewmac_32_128")
    scaled_forecasts = scale_and_cap.get_scaled_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    
    return pd.DataFrame({
        'price': price,
        'raw': raw_forecasts,
        'scalar': scalar,
        'scaled': scaled_forecasts,
        'capped': capped_forecasts
    })

start = time.perf_counter()
df_pooling = test_forecast_scalar_estimated_with_pooling()
elapsed = time.perf_counter() - start
print(f"Loaded in: {elapsed}")
df_pooling

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode

2025-12-27 18:36:29 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-27 18:36:29 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-27 18:36:29 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-27 18:36:29 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-27 18:36:30 DEBUG base_system {'stage': 'forecastScaleCap'} Getting cross sectional forecasts for scalar calculation for ewmac_32_128 over BITCOIN, CRUDE_W_mini, EUR, EUROSTX, GOLD, LIVECOW, NASDAQ, RUSSELL, SILVER, SP500, US10
2025-12-27 18:36:30 DEBUG base_system {'stage': 'rules', 'instrument_code': 'BITCOIN'} Calculating raw forecast BITCOIN for ewmac_32_128
2025-12-27 18:36:30 DEBUG base_system {'stage': 'rules', 'instrument_code': 'CRUDE_W_mini'} Calculating raw forecast CRUDE_W_mini for ewmac_32_128
2025-12-27 18:36:30 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUR'} Calculating raw forecast EUR for ewmac_32_128
2025-12-27 18:36:30 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUROSTX'} Calculating raw forecast EUROSTX for ewmac_32_128
2025-12-27 18:36:30 DEBUG base_system {'stage': 'rules', 'instrument_code': 'GOLD'} Calculating raw forecast GOLD for ewmac_32_128
2025-12-27 18:36:30 DEBUG base_system {'stage': 'rules', 'instrument_code': 'LIVECOW'} Calculating raw forecast LIVECOW for ewmac_32_128
2025-12-27 18:36:31 DEBUG base_system {'stage': 'rules', 'instrument_code': 'RUSSELL'} Calculating raw forecast RUSSELL for ewmac_32_128
2025-12-27 18:36:31 DEBUG base_system {'stage': 'rules', 'instrument_code': 'SILVER'} Calculating raw forecast SILVER for ewmac_32_128
2025-12-27 18:36:31 DEBUG base_system {'stage': 'rules', 'instrument_code': 'SP500'} Calculating raw forecast SP500 for ewmac_32_128
2025-12-27 18:36:32 DEBUG base_system {'stage': 'rules', 'instrument_code': 'US10'} Calculating raw forecast US10 for ewmac_32_128
2025-12-27 18:36:32 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128
Loaded in: 2.804944499861449

               price       raw    scalar     scaled  capped
index
1999-12-14   4959.00       NaN  3.246048        NaN     NaN
1999-12-15   5010.50       NaN  3.246106        NaN     NaN
1999-12-16   5117.00       NaN  3.246151        NaN     NaN
1999-12-17   5149.00       NaN  3.246181        NaN     NaN
1999-12-20   5181.50       NaN  3.246208        NaN     NaN
...              ...       ...       ...        ...     ...
2024-03-22  18563.75  6.218251  3.345225  20.801451    20.0
2024-03-25  18533.50  6.373547  3.345212  21.320863    20.0
2024-03-26  18480.00  6.489081  3.345190  21.707212    20.0
2024-03-27  18505.50  6.655521  3.345177  22.263895    20.0
2024-03-28  18465.00  6.777110  3.345149  22.670443    20.0

[6338 rows x 5 columns]

In [11]:
# Forecast combine (fixed weights)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-weights-fixed

def test_forecast_combination_fixed_weights():
    config = Config()
    config.instruments = portfolio_intruments
    config.use_forecast_weight_estimates=False
    #config.forecast_weights=dict(ewmac_20_60=0.5, ewmac_32_128=0.5)
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    combine= ForecastCombine()
    system = System([scale_and_cap, combine, system_rules], data, config)

    capped_forecasts_1 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_5_20")
    capped_forecasts_2 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_20_60")
    capped_forecasts_3 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts_4 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_60_150")
    capped_forecasts_5 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_100_200")
    combined_forecasts = combine.get_raw_combined_forecast_before_mapping(test_instrument_code)
    combined = combine.get_combined_forecast(test_instrument_code)

    fdm = combine.get_forecast_diversification_multiplier(test_instrument_code)

    return pd.DataFrame({
        'ewmac_5_20': capped_forecasts_1,
        'ewmac_20_60': capped_forecasts_2,
        'ewmac_32_128': capped_forecasts_3,
        'ewmac_60_150': capped_forecasts_4,
        'ewmac_100_200': capped_forecasts_5,
        'combined (weighted)': combined_forecasts,
        'forecast diversification multiplier' : fdm,
        'combined (final)': combined
    })

start = time.perf_counter()
df_pooling = test_forecast_combination_fixed_weights()
elapsed = time.perf_counter() - start
print(f"Loaded in: {elapsed}")
df_pooling

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-28 01:35:43 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-28 01:35:43 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-28 01:35:43 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-28 01:35:43 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_5_20
2025-12-28 01:35:43 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_5_20
2025-12-28 01:35:43 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_20_60
2025-12-28 01:35:43 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_20_60
2025-12-28 01:35:44 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128
2025-12-28 01:35:44 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-28 01:35:44 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_60_150
2025-12-28 01:35:44 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_60_150
2025-12-28 01:35:44 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_100_200
2025-12-28 01:35:44 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_100_200
2025-12-28 01:35:45 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Calculating forecast weights for NASDAQ
2025-12-28 01:35:45 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} WARNING: No forecast weights  - using equal weights of 0.200 over all 5 trading rules in system
2025-12-28 01:35:45 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_100_200. Using costs of zero
2025-12-28 01:35:45 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_20_60. Using costs of zero
2025-12-28 01:35:45 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_32_128. Using costs of zero
2025-12-28 01:35:45 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_5_20. Using costs of zero
2025-12-28 01:35:45 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_60_150. Using costs of zero
2025-12-28 01:35:45 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Only this set of rules ['ewmac_100_200', 'ewmac_20_60', 'ewmac_32_128', 'ewmac_5_20', 'ewmac_60_150'] is cheap enough to trade for NASDAQ
2025-12-28 01:35:45 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Using fixed FDM multiplier of 1.000 for NASDAQ
2025-12-28 01:35:45 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Calculating combined forecast for NASDAQ
2025-12-28 01:35:45 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} No mapping applied for NASDAQ
Loaded in: 2.287995500024408

,ewmac_5_20,ewmac_20_60,ewmac_32_128,ewmac_60_150,ewmac_100_200,combined (weighted),forecast diversification multiplier,combined (final)
index,,,,,,,,
1999-12-14,NaN,NaN,NaN,NaN,NaN,0.000000,1.0,0.000000
1999-12-15,NaN,NaN,NaN,NaN,NaN,0.000000,1.0,0.000000
1999-12-16,NaN,NaN,NaN,NaN,NaN,0.000000,1.0,0.000000
1999-12-17,NaN,NaN,NaN,NaN,NaN,0.000000,1.0,0.000000
1999-12-20,NaN,NaN,NaN,NaN,NaN,0.000000,1.0,0.000000
...,...,...,...,...,...,...,...,...
2024-03-22,0.910278,2.632258,6.218251,5.430158,5.057385,4.049666,1.0,4.049666
2024-03-25,0.938249,2.693577,6.373547,5.578664,5.207074,4.158222,1.0,4.158222
2024-03-26,0.849663,2.717678,6.489081,5.701951,5.337783,4.219231,1.0,4.219231
2024-03-27,0.819115,2.766787,6.655521,5.868886,5.509537,4.323969,1.0,4.323969
2024-03-28,0.712794,2.781179,6.777110,6.004301,5.655778,4.386232,1.0,4.386232

In [ ]:
# Forecast combination (estimated weights)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-weights-estimated

# TODO

In [12]:
# Forecast combination (fixed diversification multiplier)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-diversification-multiplier-fixed

def test_forecast_combination_fixed():
    config = Config()
    config.instruments = portfolio_intruments
    config.use_forecast_div_mult_estimates=False
    config.forecast_div_multiplier = 1.2
    #config.forecast_weights=dict(ewmac_20_60=0.5, ewmac_32_128=0.5)
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    combine= ForecastCombine()
    system = System([scale_and_cap, combine, system_rules], data, config)

    capped_forecasts_1 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_5_20")
    capped_forecasts_2 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_20_60")
    capped_forecasts_3 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts_4 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_60_150")
    capped_forecasts_5 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_100_200")
    combined_forecasts = combine.get_raw_combined_forecast_before_mapping(test_instrument_code)
    combined = combine.get_combined_forecast(test_instrument_code)

    fdm = combine.get_forecast_diversification_multiplier(test_instrument_code)

    return pd.DataFrame({
        'ewmac_5_20': capped_forecasts_1,
        'ewmac_20_60': capped_forecasts_2,
        'ewmac_32_128': capped_forecasts_3,
        'ewmac_60_150': capped_forecasts_4,
        'ewmac_100_200': capped_forecasts_5,
        'combined (weighted)': combined_forecasts,
        'forecast diversification multiplier' : fdm,
        'combined (final)': combined
    })

start = time.perf_counter()
df_pooling = test_forecast_combination_fixed()
elapsed = time.perf_counter() - start
print(f"Loaded in: {elapsed}")
df_pooling

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-28 01:36:19 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-28 01:36:19 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-28 01:36:19 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-28 01:36:19 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_5_20
2025-12-28 01:36:19 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_5_20
2025-12-28 01:36:19 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_20_60
2025-12-28 01:36:19 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_20_60
2025-12-28 01:36:19 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128
2025-12-28 01:36:19 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-28 01:36:20 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_60_150
2025-12-28 01:36:20 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_60_150
2025-12-28 01:36:20 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_100_200
2025-12-28 01:36:20 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_100_200
2025-12-28 01:36:20 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Calculating forecast weights for NASDAQ
2025-12-28 01:36:20 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} WARNING: No forecast weights  - using equal weights of 0.200 over all 5 trading rules in system
2025-12-28 01:36:20 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_100_200. Using costs of zero
2025-12-28 01:36:20 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_20_60. Using costs of zero
2025-12-28 01:36:20 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_32_128. Using costs of zero
2025-12-28 01:36:20 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_5_20. Using costs of zero
2025-12-28 01:36:20 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_60_150. Using costs of zero
2025-12-28 01:36:21 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Only this set of rules ['ewmac_100_200', 'ewmac_20_60', 'ewmac_32_128', 'ewmac_5_20', 'ewmac_60_150'] is cheap enough to trade for NASDAQ
2025-12-28 01:36:21 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Using fixed FDM multiplier of 1.200 for NASDAQ
2025-12-28 01:36:21 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Calculating combined forecast for NASDAQ
2025-12-28 01:36:21 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} No mapping applied for NASDAQ
Loaded in: 2.1383247000630945

,ewmac_5_20,ewmac_20_60,ewmac_32_128,ewmac_60_150,ewmac_100_200,combined (weighted),forecast diversification multiplier,combined (final)
index,,,,,,,,
1999-12-14,NaN,NaN,NaN,NaN,NaN,0.000000,1.2,0.000000
1999-12-15,NaN,NaN,NaN,NaN,NaN,0.000000,1.2,0.000000
1999-12-16,NaN,NaN,NaN,NaN,NaN,0.000000,1.2,0.000000
1999-12-17,NaN,NaN,NaN,NaN,NaN,0.000000,1.2,0.000000
1999-12-20,NaN,NaN,NaN,NaN,NaN,0.000000,1.2,0.000000
...,...,...,...,...,...,...,...,...
2024-03-22,0.910278,2.632258,6.218251,5.430158,5.057385,4.859599,1.2,4.859599
2024-03-25,0.938249,2.693577,6.373547,5.578664,5.207074,4.989867,1.2,4.989867
2024-03-26,0.849663,2.717678,6.489081,5.701951,5.337783,5.063077,1.2,5.063077
2024-03-27,0.819115,2.766787,6.655521,5.868886,5.509537,5.188763,1.2,5.188763
2024-03-28,0.712794,2.781179,6.777110,6.004301,5.655778,5.263479,1.2,5.263479

In [ ]:
# Forecast combination (estimated diversification multiplier)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-diversification-multiplier-estimated

# TODO

In [8]:
# Position sizing stage
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#position-sizing-stage

def test_position_sizing_stage():
    config = Config()
    config.instruments = portfolio_intruments
    config.use_forecast_weight_estimates=False
    #config.forecast_weights=dict(ewmac_20_60=0.5, ewmac_32_128=0.5)
    config.percentage_vol_target=25.0
    config.notional_trading_capital=1000000
    config.base_currency="USD"

    raw_data = RawData()
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    combine = ForecastCombine()
    position_sizing = PositionSizing()

    system = System([raw_data, scale_and_cap, combine, position_sizing, system_rules], data, config)

    combined_forecasts = combine.get_raw_combined_forecast_before_mapping(test_instrument_code)
   
    # Per vedere alcuni valori intermedi è necessario effettuare alcune operazioni direttamente qui,
    # sono copiate dai metodi interni di PositionSizing
    fx_volatility = position_sizing.get_instrument_currency_vol(test_instrument_code) 

    fx_rate = position_sizing.get_fx_rate(test_instrument_code)
    fx_rate = fx_rate.reindex(fx_volatility.index, method="ffill")

    instrument_value_volatility = position_sizing.get_instrument_value_vol(test_instrument_code)

    cash_vol_target = position_sizing.get_daily_cash_vol_target()
    volatility_scalar = cash_vol_target / instrument_value_volatility

    subsystem_position = position_sizing.get_subsystem_position(test_instrument_code)

    return pd.DataFrame({

        'combined (weighted)': combined_forecasts,
        'fx_rates': fx_rate,
        'fx_volatility': fx_volatility,
        'instrument_value_volatility': instrument_value_volatility,
        'cash_vol_target': cash_vol_target,
        'volatility_scalar': volatility_scalar,
        'subsystem_position': subsystem_position
    })

start = time.perf_counter()
df_pooling = test_position_sizing_stage()
elapsed = time.perf_counter() - start
print(f"Loaded in: {elapsed}")
df_pooling

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-27 18:36:33 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-27 18:36:33 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-27 18:36:33 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-27 18:36:33 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_100_200
2025-12-27 18:36:33 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_100_200
2025-12-27 18:36:33 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_20_60
2025-12-27 18:36:33 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_20_60
2025-12-27 18:36:33 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128
2025-12-27 18:36:33 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-27 18:36:34 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_5_20
2025-12-27 18:36:34 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_5_20
2025-12-27 18:36:34 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_60_150
2025-12-27 18:36:34 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_60_150
2025-12-27 18:36:34 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Calculating forecast weights for NASDAQ
2025-12-27 18:36:34 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} WARNING: No forecast weights  - using equal weights of 0.200 over all 5 trading rules in system
2025-12-27 18:36:34 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_100_200. Using costs of zero
2025-12-27 18:36:34 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_20_60. Using costs of zero
2025-12-27 18:36:34 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_32_128. Using costs of zero
2025-12-27 18:36:34 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_5_20. Using costs of zero
2025-12-27 18:36:34 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_60_150. Using costs of zero
2025-12-27 18:36:34 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Only this set of rules ['ewmac_100_200', 'ewmac_20_60', 'ewmac_32_128', 'ewmac_5_20', 'ewmac_60_150'] is cheap enough to trade for NASDAQ
2025-12-27 18:36:34 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Using fixed FDM multiplier of 1.000 for NASDAQ
2025-12-27 18:36:34 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'NASDAQ'} Calculating instrument currency vol for NASDAQ
2025-12-27 18:36:34 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'NASDAQ'} Calculating daily volatility for NASDAQ
2025-12-27 18:36:34 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'NASDAQ'} Calculating daily prices for NASDAQ
2025-12-27 18:36:35 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'NASDAQ'} Calculating instrument value vol for NASDAQ
2025-12-27 18:36:35 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'NASDAQ'} Calculating subsystem position for NASDAQ
2025-12-27 18:36:35 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'NASDAQ'} Calculating volatility scalar for NASDAQ
2025-12-27 18:36:35 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Calculating combined forecast for NASDAQ
2025-12-27 18:36:35 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} No mapping applied for NASDAQ
Loaded in: 1.5617579999379814

,combined (weighted),fx_rates,fx_volatility,instrument_value_volatility,cash_vol_target,volatility_scalar,subsystem_position
index,,,,,,,
1999-12-14,0.000000,1.0,NaN,NaN,15625.0,NaN,NaN
1999-12-15,0.000000,1.0,NaN,NaN,15625.0,NaN,NaN
1999-12-16,0.000000,1.0,NaN,NaN,15625.0,NaN,NaN
1999-12-17,0.000000,1.0,NaN,NaN,15625.0,NaN,NaN
1999-12-20,0.000000,1.0,NaN,NaN,15625.0,NaN,NaN
...,...,...,...,...,...,...,...
2024-03-22,4.049666,1.0,3044.757194,3044.757194,15625.0,5.131772,2.078196
2024-03-25,4.158222,1.0,2985.874293,2985.874293,15625.0,5.232973,2.175987
2024-03-26,4.219231,1.0,2935.859699,2935.859699,15625.0,5.322121,2.245526
2024-03-27,4.323969,1.0,2872.485593,2872.485593,15625.0,5.439540,2.352040
2024-03-28,4.386232,1.0,2820.565443,2820.565443,15625.0,5.539669,2.429828

In [9]:
# Portfolio stage (fixed weights and instrument diversification multiplier)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#using-fixed-weights-and-instrument-diversification-multipliersystemsportfoliopy

from systems.portfolio import Portfolios


def test_portfolio_stage():
    config = Config()
    config.instruments = portfolio_intruments
    config.use_forecast_weight_estimates=False
    #config.forecast_weights=dict(ewmac_20_60=0.5, ewmac_32_128=0.5)
    config.percentage_vol_target=25.0
    config.notional_trading_capital=1000000
    config.base_currency="USD"
    config.instrument_div_multiplier = 1.2

    raw_data = RawData()
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    combine= ForecastCombine()
    position_sizing = PositionSizing()
    portfolio = Portfolios()

    system = System([raw_data, scale_and_cap, combine, position_sizing, portfolio, system_rules], data, config)

    combined_forecasts = combine.get_raw_combined_forecast_before_mapping(test_instrument_code)  
    subsystem_position = position_sizing.get_subsystem_position(test_instrument_code)
    
    # Dictionary to store notional positions for each instrument
    df_data = { }
    
    # Loop through each instrument and get notional position
    for instrument in portfolio_intruments:
        portfolio_notional_positions = portfolio.get_notional_position(instrument)
        df_data[f'portfolio_notional_position_{instrument}'] = portfolio_notional_positions

    return pd.DataFrame(df_data)

start = time.perf_counter()
df_pooling = test_portfolio_stage()
elapsed = time.perf_counter() - start
print(f"Loaded in: {elapsed}")
df_pooling

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-27 18:36:35 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-27 18:36:35 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-27 18:36:35 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-27 18:36:35 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_100_200
2025-12-27 18:36:35 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_100_200
2025-12-27 18:36:35 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_20_60
2025-12-27 18:36:35 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_20_60
2025-12-27 18:36:35 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128
2025-12-27 18:36:35 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-27 18:36:35 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_5_20
2025-12-27 18:36:35 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_5_20
2025-12-27 18:36:35 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_60_150
2025-12-27 18:36:35 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_60_150
2025-12-27 18:36:36 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Calculating forecast weights for NASDAQ
2025-12-27 18:36:36 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} WARNING: No forecast weights  - using equal weights of 0.200 over all 5 trading rules in system
2025-12-27 18:36:36 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_100_200. Using costs of zero
2025-12-27 18:36:36 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_20_60. Using costs of zero
2025-12-27 18:36:36 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_32_128. Using costs of zero
2025-12-27 18:36:36 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_5_20. Using costs of zero
2025-12-27 18:36:36 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_60_150. Using costs of zero
2025-12-27 18:36:36 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Only this set of rules ['ewmac_100_200', 'ewmac_20_60', 'ewmac_32_128', 'ewmac_5_20', 'ewmac_60_150'] is cheap enough to trade for NASDAQ
2025-12-27 18:36:36 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Using fixed FDM multiplier of 1.000 for NASDAQ
2025-12-27 18:36:36 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'NASDAQ'} Calculating subsystem position for NASDAQ
2025-12-27 18:36:36 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'NASDAQ'} Calculating volatility scalar for NASDAQ
2025-12-27 18:36:36 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'NASDAQ'} Calculating instrument value vol for NASDAQ
2025-12-27 18:36:36 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'NASDAQ'} Calculating instrument currency vol for NASDAQ
2025-12-27 18:36:36 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'NASDAQ'} Calculating daily volatility for NASDAQ
2025-12-27 18:36:36 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'NASDAQ'} Calculating daily prices for NASDAQ
2025-12-27 18:36:36 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Calculating combined forecast for NASDAQ
2025-12-27 18:36:36 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} No mapping applied for NASDAQ
2025-12-27 18:36:36 DEBUG base_system {'stage': 'portfolio', 'instrument_code': 'NASDAQ'} Calculating notional position for NASDAQ
2025-12-27 18:36:36 INFO base_system {'stage': 'portfolio', 'instrument_code': 'NASDAQ'} Calculating instrument weights
2025-12-27 18:36:36 DEBUG base_system {'stage': 'portfolio', 'instrument_code': 'NASDAQ'} Calculating raw instrument weights
2025-12-27 18:36:36 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-27 18:36:36 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-27 18:36:36 DEBUG base_system Following instruments are marked as 'bad_markets':  ['BAD_EXAMPLE']
2025-12-27 18:36:36 DEBUG base_system Following instruments have restricted trading:  ['RESTRICTED_EXAMPLE']
2025-12-27 18:36:36 DEBUG base_system Following instruments marked as not trading []
2025-12-27 18:36:36 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'BITCOIN'} Calculating subsystem position for BITCOIN
2025-12-27 18:36:36 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'BITCOIN'} Calculating volatility scalar for BITCOIN
2025-12-27 18:36:36 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'BITCOIN'} Calculating instrument value vol for BITCOIN
2025-12-27 18:36:36 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'BITCOIN'} Calculating instrument currency vol for BITCOIN
2025-12-27 18:36:36 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'BITCOIN'} Calculating daily volatility for BITCOIN
2025-12-27 18:36:36 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'BITCOIN'} Calculating daily prices for BITCOIN
2025-12-27 18:36:36 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} Calculating combined forecast for BITCOIN
2025-12-27 18:36:36 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'BITCOIN'} Calculating capped forecast for BITCOIN ewmac_100_200
2025-12-27 18:36:36 DEBUG base_system {'stage': 'rules', 'instrument_code': 'BITCOIN'} Calculating raw forecast BITCOIN for ewmac_100_200
2025-12-27 18:36:36 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'BITCOIN'} Calculating capped forecast for BITCOIN ewmac_20_60
2025-12-27 18:36:36 DEBUG base_system {'stage': 'rules', 'instrument_code': 'BITCOIN'} Calculating raw forecast BITCOIN for ewmac_20_60
2025-12-27 18:36:37 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'BITCOIN'} Calculating capped forecast for BITCOIN ewmac_32_128
2025-12-27 18:36:37 DEBUG base_system {'stage': 'rules', 'instrument_code': 'BITCOIN'} Calculating raw forecast BITCOIN for ewmac_32_128
2025-12-27 18:36:37 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'BITCOIN'} Calculating capped forecast for BITCOIN ewmac_5_20
2025-12-27 18:36:37 DEBUG base_system {'stage': 'rules', 'instrument_code': 'BITCOIN'} Calculating raw forecast BITCOIN for ewmac_5_20
2025-12-27 18:36:37 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'BITCOIN'} Calculating capped forecast for BITCOIN ewmac_60_150
2025-12-27 18:36:37 DEBUG base_system {'stage': 'rules', 'instrument_code': 'BITCOIN'} Calculating raw forecast BITCOIN for ewmac_60_150
2025-12-27 18:36:37 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} Calculating forecast weights for BITCOIN
2025-12-27 18:36:37 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} WARNING: No forecast weights  - using equal weights of 0.200 over all 5 trading rules in system
2025-12-27 18:36:37 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} You need an accounts stage in the system to estimate forecast costs for BITCOIN ewmac_100_200. Using costs of zero
2025-12-27 18:36:37 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} You need an accounts stage in the system to estimate forecast costs for BITCOIN ewmac_20_60. Using costs of zero
2025-12-27 18:36:37 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} You need an accounts stage in the system to estimate forecast costs for BITCOIN ewmac_32_128. Using costs of zero
2025-12-27 18:36:37 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} You need an accounts stage in the system to estimate forecast costs for BITCOIN ewmac_5_20. Using costs of zero
2025-12-27 18:36:37 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} You need an accounts stage in the system to estimate forecast costs for BITCOIN ewmac_60_150. Using costs of zero
2025-12-27 18:36:37 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} Only this set of rules ['ewmac_100_200', 'ewmac_20_60', 'ewmac_32_128', 'ewmac_5_20', 'ewmac_60_150'] is cheap enough to trade for BITCOIN
2025-12-27 18:36:37 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} Using fixed FDM multiplier of 1.000 for BITCOIN
2025-12-27 18:36:37 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'BITCOIN'} No mapping applied for BITCOIN
2025-12-27 18:36:37 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'CRUDE_W_mini'} Calculating subsystem position for CRUDE_W_mini
2025-12-27 18:36:37 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'CRUDE_W_mini'} Calculating volatility scalar for CRUDE_W_mini
2025-12-27 18:36:37 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'CRUDE_W_mini'} Calculating instrument value vol for CRUDE_W_mini
2025-12-27 18:36:37 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'CRUDE_W_mini'} Calculating instrument currency vol for CRUDE_W_mini
2025-12-27 18:36:37 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'CRUDE_W_mini'} Calculating daily volatility for CRUDE_W_mini
2025-12-27 18:36:37 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'CRUDE_W_mini'} Calculating daily prices for CRUDE_W_mini
2025-12-27 18:36:37 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} Calculating combined forecast for CRUDE_W_mini
2025-12-27 18:36:37 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'CRUDE_W_mini'} Calculating capped forecast for CRUDE_W_mini ewmac_100_200
2025-12-27 18:36:37 DEBUG base_system {'stage': 'rules', 'instrument_code': 'CRUDE_W_mini'} Calculating raw forecast CRUDE_W_mini for ewmac_100_200
2025-12-27 18:36:37 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'CRUDE_W_mini'} Calculating capped forecast for CRUDE_W_mini ewmac_20_60
2025-12-27 18:36:37 DEBUG base_system {'stage': 'rules', 'instrument_code': 'CRUDE_W_mini'} Calculating raw forecast CRUDE_W_mini for ewmac_20_60
2025-12-27 18:36:38 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'CRUDE_W_mini'} Calculating capped forecast for CRUDE_W_mini ewmac_32_128
2025-12-27 18:36:38 DEBUG base_system {'stage': 'rules', 'instrument_code': 'CRUDE_W_mini'} Calculating raw forecast CRUDE_W_mini for ewmac_32_128
2025-12-27 18:36:38 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'CRUDE_W_mini'} Calculating capped forecast for CRUDE_W_mini ewmac_5_20
2025-12-27 18:36:38 DEBUG base_system {'stage': 'rules', 'instrument_code': 'CRUDE_W_mini'} Calculating raw forecast CRUDE_W_mini for ewmac_5_20
2025-12-27 18:36:38 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'CRUDE_W_mini'} Calculating capped forecast for CRUDE_W_mini ewmac_60_150
2025-12-27 18:36:38 DEBUG base_system {'stage': 'rules', 'instrument_code': 'CRUDE_W_mini'} Calculating raw forecast CRUDE_W_mini for ewmac_60_150
2025-12-27 18:36:38 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} Calculating forecast weights for CRUDE_W_mini
2025-12-27 18:36:38 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} WARNING: No forecast weights  - using equal weights of 0.200 over all 5 trading rules in system
2025-12-27 18:36:38 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} You need an accounts stage in the system to estimate forecast costs for CRUDE_W_mini ewmac_100_200. Using costs of zero
2025-12-27 18:36:38 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} You need an accounts stage in the system to estimate forecast costs for CRUDE_W_mini ewmac_20_60. Using costs of zero
2025-12-27 18:36:38 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} You need an accounts stage in the system to estimate forecast costs for CRUDE_W_mini ewmac_32_128. Using costs of zero
2025-12-27 18:36:38 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} You need an accounts stage in the system to estimate forecast costs for CRUDE_W_mini ewmac_5_20. Using costs of zero
2025-12-27 18:36:38 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} You need an accounts stage in the system to estimate forecast costs for CRUDE_W_mini ewmac_60_150. Using costs of zero
2025-12-27 18:36:38 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} Only this set of rules ['ewmac_100_200', 'ewmac_20_60', 'ewmac_32_128', 'ewmac_5_20', 'ewmac_60_150'] is cheap enough to trade for CRUDE_W_mini
2025-12-27 18:36:38 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} Using fixed FDM multiplier of 1.000 for CRUDE_W_mini
2025-12-27 18:36:38 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'CRUDE_W_mini'} No mapping applied for CRUDE_W_mini
2025-12-27 18:36:38 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'EUR'} Calculating subsystem position for EUR
2025-12-27 18:36:38 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'EUR'} Calculating volatility scalar for EUR
2025-12-27 18:36:38 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'EUR'} Calculating instrument value vol for EUR
2025-12-27 18:36:38 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'EUR'} Calculating instrument currency vol for EUR
2025-12-27 18:36:39 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'EUR'} Calculating daily volatility for EUR
2025-12-27 18:36:39 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'EUR'} Calculating daily prices for EUR
2025-12-27 18:36:39 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} Calculating combined forecast for EUR
2025-12-27 18:36:39 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'EUR'} Calculating capped forecast for EUR ewmac_100_200
2025-12-27 18:36:39 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUR'} Calculating raw forecast EUR for ewmac_100_200
2025-12-27 18:36:39 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'EUR'} Calculating capped forecast for EUR ewmac_20_60
2025-12-27 18:36:39 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUR'} Calculating raw forecast EUR for ewmac_20_60
2025-12-27 18:36:39 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'EUR'} Calculating capped forecast for EUR ewmac_32_128
2025-12-27 18:36:39 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUR'} Calculating raw forecast EUR for ewmac_32_128
2025-12-27 18:36:39 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'EUR'} Calculating capped forecast for EUR ewmac_5_20
2025-12-27 18:36:39 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUR'} Calculating raw forecast EUR for ewmac_5_20
2025-12-27 18:36:39 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'EUR'} Calculating capped forecast for EUR ewmac_60_150
2025-12-27 18:36:39 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUR'} Calculating raw forecast EUR for ewmac_60_150
2025-12-27 18:36:40 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} Calculating forecast weights for EUR
2025-12-27 18:36:40 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} WARNING: No forecast weights  - using equal weights of 0.200 over all 5 trading rules in system
2025-12-27 18:36:40 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} You need an accounts stage in the system to estimate forecast costs for EUR ewmac_100_200. Using costs of zero
2025-12-27 18:36:40 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} You need an accounts stage in the system to estimate forecast costs for EUR ewmac_20_60. Using costs of zero
2025-12-27 18:36:40 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} You need an accounts stage in the system to estimate forecast costs for EUR ewmac_32_128. Using costs of zero
2025-12-27 18:36:40 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} You need an accounts stage in the system to estimate forecast costs for EUR ewmac_5_20. Using costs of zero
2025-12-27 18:36:40 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} You need an accounts stage in the system to estimate forecast costs for EUR ewmac_60_150. Using costs of zero
2025-12-27 18:36:40 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} Only this set of rules ['ewmac_100_200', 'ewmac_20_60', 'ewmac_32_128', 'ewmac_5_20', 'ewmac_60_150'] is cheap enough to trade for EUR
2025-12-27 18:36:40 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} Using fixed FDM multiplier of 1.000 for EUR
2025-12-27 18:36:40 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'EUR'} No mapping applied for EUR
2025-12-27 18:36:40 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'EUROSTX'} Calculating subsystem position for EUROSTX
2025-12-27 18:36:40 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'EUROSTX'} Calculating volatility scalar for EUROSTX
2025-12-27 18:36:40 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'EUROSTX'} Calculating instrument value vol for EUROSTX
2025-12-27 18:36:40 DEBUG base_system {'stage': 'positionSize', 'instrument_code': 'EUROSTX'} Calculating instrument currency vol for EUROSTX
2025-12-27 18:36:40 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'EUROSTX'} Calculating daily volatility for EUROSTX
2025-12-27 18:36:40 DEBUG base_system {'stage': 'rawdata', 'instrument_code': 'EUROSTX'} Calculating daily prices for EUROSTX
2025-12-27 18:36:40 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'EUROSTX'} Calculating combined forecast for EUROSTX
2025-12-27 18:36:40 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'EUROSTX'} Calculating capped forecast for EUROSTX ewmac_100_200
2025-12-27 18:36:40 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUROSTX'} Calculating raw forecast EUROSTX for ewmac_100_200
2025-12-27 18:36:40 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'EUROSTX'} Calculating capped forecast for EUROSTX ewmac_20_60
2025-12-27 18:36:40 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUROSTX'} Calculating raw forecast EUROSTX for ewmac_20_60

,portfolio_notional_position_NASDAQ,portfolio_notional_position_SP500,portfolio_notional_position_US10,portfolio_notional_position_RUSSELL,portfolio_notional_position_EUR,portfolio_notional_position_GOLD,portfolio_notional_position_SILVER,portfolio_notional_position_EUROSTX,portfolio_notional_position_BITCOIN,portfolio_notional_position_CRUDE_W_mini,portfolio_notional_position_LIVECOW
index,,,,,,,,,,,
1970-06-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-06-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-06-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-06-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-06-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2024-03-22,0.226712,0.573393,-0.446162,2.481932,-0.082078,0.284473,0.278929,3.051635,3.088861,0.374491,0.376756
2024-03-25,0.237380,0.592982,-0.446205,2.620084,-0.099357,0.299585,0.281488,3.238163,2.293270,0.401910,0.326673
2024-03-26,0.244966,0.611570,-0.447933,2.742063,-0.115760,0.319008,0.263632,3.345915,2.365605,0.405231,0.181849
2024-03-27,0.256586,0.621380,-0.423269,2.675124,-0.137042,0.338591,0.272547,3.448511,2.463635,0.422636,0.136230
2024-03-28,0.265072,0.649769,-0.425280,2.958091,-0.176606,0.300886,0.306058,3.552962,2.582912,0.458091,0.121298