In [25]:
import pandas as pd
import time
from systems.forecasting import TradingRule, Rules
from systems.provided.rules.ewmac import ewmac_forecast_with_defaults as ewmac
from sysdata.config.configdata import Config
from systems.forecast_combine import ForecastCombine
from systems.basesystem import System
from systems.accounts.accounts_stage import Account
from systems.forecast_scale_cap import ForecastScaleCap
from systems.rawdata import RawData
from systems.positionsizing import PositionSizing
from sysdata.sim.csv_futures_sim_data import csvFuturesSimData

# my_account = Account()
# scale_and_cap = ForecastScaleCap()
# combiner = ForecastCombine()
# raw_data = RawData()
# position_size = PositionSizing()
# data = csvFuturesSimData()

# instruments
portfolio_intruments =  [
     "NASDAQ",
     "SP500",
     "US10",
     "RUSSELL",
     "EUR",
     "GOLD",
     "SILVER",
     "EUROSTX",
     "BITCOIN",
     "CRUDE_W_mini",
     "LIVECOW"
     ]

test_instrument_code = "NASDAQ"
main_rule_name = "ewmac_32_128"

# define rules
ewmac_5_20 = TradingRule((ewmac, [], dict(Lfast=5, Lslow=20)))
ewmac_20_60 = TradingRule((ewmac, [], dict(Lfast=20, Lslow=60)))
ewmac_32_128 = TradingRule((ewmac, [], dict(Lfast=32, Lslow=128)))
ewmac_60_150 = TradingRule((ewmac, [], dict(Lfast=60, Lslow=150)))
ewmac_100_200 = TradingRule((ewmac, [], dict(Lfast=100, Lslow=200)))

system_rules = Rules(dict(ewmac_5_20=ewmac_5_20, 
                      ewmac_20_60=ewmac_20_60,
                      ewmac_32_128=ewmac_32_128,
                      ewmac_60_150=ewmac_60_150,
                      ewmac_100_200=ewmac_100_200))

In [ ]:
# Forecast scalar (fixed)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-scalar-fixed

def test_forecast_scalar_fixed():
    config = Config()
    config.use_forecast_scale_estimates = False
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    system = System([scale_and_cap, system_rules], data, config)
    
    raw_forecasts = system_rules.get_raw_forecast(test_instrument_code, "ewmac_32_128") #system.rules.get_raw_forecast(test_instrument_code, "ewmac_32_128")
    scalar = scale_and_cap.get_forecast_scalar(test_instrument_code, "ewmac_32_128")
    scaled_forecasts = scale_and_cap.get_scaled_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    
    return pd.DataFrame({
        'raw': raw_forecasts,
        'scalar': scalar,
        'scaled': scaled_forecasts,
        'capped': capped_forecasts
    })

test_forecast_scalar_fixed().tail(10)

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-08 21:27:28 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-08 21:27:28 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-08 21:27:28 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-08 21:27:28 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-08 21:27:28 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128

                 raw  scalar    scaled    capped
index
2024-03-15  5.975783     1.0  5.975783  5.975783
2024-03-18  5.932453     1.0  5.932453  5.932453
2024-03-19  6.049077     1.0  6.049077  6.049077
2024-03-20  5.847705     1.0  5.847705  5.847705
2024-03-21  6.042689     1.0  6.042689  6.042689
2024-03-22  6.218251     1.0  6.218251  6.218251
2024-03-25  6.373547     1.0  6.373547  6.373547
2024-03-26  6.489081     1.0  6.489081  6.489081
2024-03-27  6.655521     1.0  6.655521  6.655521
2024-03-28  6.777110     1.0  6.777110  6.777110

In [ ]:
# Forecast scalar (fixed)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-scalar-fixed

def test_forecast_scalar_fixed_per_rule():
    config = Config()
    config.use_forecast_scale_estimates = False
    config.forecast_scalars=dict(ewmac_32_128=3)
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    system = System([scale_and_cap, system_rules], data, config)
    
    raw_forecasts = system_rules.get_raw_forecast(test_instrument_code, "ewmac_32_128") #system.rules.get_raw_forecast(test_instrument_code, "ewmac_32_128")
    scalar = scale_and_cap.get_forecast_scalar(test_instrument_code, "ewmac_32_128")
    scaled_forecasts = scale_and_cap.get_scaled_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    
    return pd.DataFrame({
        'raw': raw_forecasts,
        'scalar': scalar,
        'scaled': scaled_forecasts,
        'capped': capped_forecasts
    })

test_forecast_scalar_fixed_per_rule().tail(10)

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-08 21:27:28 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-08 21:27:28 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-08 21:27:28 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-08 21:27:28 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-08 21:27:29 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128

                 raw  scalar    scaled    capped
index
2024-03-15  5.975783     1.0  5.975783  5.975783
2024-03-18  5.932453     1.0  5.932453  5.932453
2024-03-19  6.049077     1.0  6.049077  6.049077
2024-03-20  5.847705     1.0  5.847705  5.847705
2024-03-21  6.042689     1.0  6.042689  6.042689
2024-03-22  6.218251     1.0  6.218251  6.218251
2024-03-25  6.373547     1.0  6.373547  6.373547
2024-03-26  6.489081     1.0  6.489081  6.489081
2024-03-27  6.655521     1.0  6.655521  6.655521
2024-03-28  6.777110     1.0  6.777110  6.777110

In [ ]:
# Forecast scalar (estimated)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-scalar-estimated

# Nota: per qualche motivo il risultato in c# è leggermente diverso da quello di pysystemtrade a causa di questa funzione:
# avg_abs_value = x.rolling(window=window, min_periods=min_periods).mean()

# L'input di questa funzione sembra corrispondere, a parte per alcuni NaN iniziali che in c# sono già stati rimossi
# Credo sia dovuto all'approssimazione ma non sono convinto.

def test_forecast_scalar_estimated():
    config = Config()
    config.use_forecast_scale_estimates=True
    config.forecast_scalar_estimate=dict(pool_instruments=False, func="sysquant.estimators.forecast_scalar.forecast_scalar", window=250000, min_periods=500, backfill=True)
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    system = System([scale_and_cap, system_rules], data, config)
    
    raw_forecasts = system_rules.get_raw_forecast(test_instrument_code, "ewmac_32_128") #system.rules.get_raw_forecast(test_instrument_code, "ewmac_32_128")
    scalar = scale_and_cap.get_forecast_scalar(test_instrument_code, "ewmac_32_128")
    scaled_forecasts = scale_and_cap.get_scaled_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    
    return pd.DataFrame({
        'raw': raw_forecasts,
        'scalar': scalar,
        'scaled': scaled_forecasts,
        'capped': capped_forecasts
    })

start = time.perf_counter()
df_pooling = test_forecast_scalar_estimated().tail(10)
elapsed = time.perf_counter() - start
print(f"Loaded in: {elapsed}")
df_pooling

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-08 21:27:29 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-08 21:27:29 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-08 21:27:29 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-08 21:27:29 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-08 21:27:29 DEBUG base_system {'stage': 'forecastScaleCap'} Getting cross sectional forecasts for scalar calculation for ewmac_32_128 over NASDAQ
2025-12-08 21:27:29 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128
Loaded in: 0.5135646000271663

                 raw    scalar     scaled     capped
index
2024-03-15  5.975783  2.744562  16.400904  16.400904
2024-03-18  5.932453  2.744289  16.280366  16.280366
2024-03-19  6.049077  2.744002  16.598680  16.598680
2024-03-20  5.847705  2.743740  16.044581  16.044581
2024-03-21  6.042689  2.743454  16.577842  16.577842
2024-03-22  6.218251  2.743148  17.057581  17.057581
2024-03-25  6.373547  2.742823  17.481513  17.481513
2024-03-26  6.489081  2.742485  17.796208  17.796208
2024-03-27  6.655521  2.742127  18.250286  18.250286
2024-03-28  6.777110  2.741755  18.581176  18.581176

In [ ]:
# Forecast scalar (estimated with pooling)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-scalar-estimated

# Nota: per qualche motivo il risultato in c# è leggermente diverso da quello di pysystemtrade a causa di questa funzione:
# avg_abs_value = x.rolling(window=window, min_periods=min_periods).mean()

# L'input di questa funzione sembra corrispondere, a parte per alcuni NaN iniziali che in c# sono già stati rimossi
# Credo sia dovuto all'approssimazione ma non sono convinto.

def test_forecast_scalar_estimated_with_pooling():
    config = Config()
    config.instruments = portfolio_intruments
    config.use_forecast_scale_estimates=True
    config.forecast_scalar_estimate=dict(pool_instruments=True, func="sysquant.estimators.forecast_scalar.forecast_scalar", window=250000, min_periods=500, backfill=True)
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    system = System([scale_and_cap, system_rules], data, config)
    
    raw_forecasts = system_rules.get_raw_forecast(test_instrument_code, "ewmac_32_128") #system.rules.get_raw_forecast(test_instrument_code, "ewmac_32_128")
    scalar = scale_and_cap.get_forecast_scalar(test_instrument_code, "ewmac_32_128")
    scaled_forecasts = scale_and_cap.get_scaled_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    
    return pd.DataFrame({
        'raw': raw_forecasts,
        'scalar': scalar,
        'scaled': scaled_forecasts,
        'capped': capped_forecasts
    })

start = time.perf_counter()
df_pooling = test_forecast_scalar_estimated_with_pooling().tail(10)
elapsed = time.perf_counter() - start
print(f"Loaded in: {elapsed}")
df_pooling

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-08 21:27:29 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-08 21:27:29 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-08 21:27:29 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-08 21:27:29 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-08 21:27:30 DEBUG base_system {'stage': 'forecastScaleCap'} Getting cross sectional forecasts for scalar calculation for ewmac_32_128 over BITCOIN, CRUDE_W_mini, EUR, EUROSTX, GOLD, LIVECOW, NASDAQ, RUSSELL, SILVER, SP500, US10
2025-12-08 21:27:30 DEBUG base_system {'stage': 'rules', 'instrument_code': 'BITCOIN'} Calculating raw forecast BITCOIN for ewmac_32_128
2025-12-08 21:27:30 DEBUG base_system {'stage': 'rules', 'instrument_code': 'CRUDE_W_mini'} Calculating raw forecast CRUDE_W_mini for ewmac_32_128
2025-12-08 21:27:30 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUR'} Calculating raw forecast EUR for ewmac_32_128
2025-12-08 21:27:30 DEBUG base_system {'stage': 'rules', 'instrument_code': 'EUROSTX'} Calculating raw forecast EUROSTX for ewmac_32_128
2025-12-08 21:27:31 DEBUG base_system {'stage': 'rules', 'instrument_code': 'GOLD'} Calculating raw forecast GOLD for ewmac_32_128
2025-12-08 21:27:31 DEBUG base_system {'stage': 'rules', 'instrument_code': 'LIVECOW'} Calculating raw forecast LIVECOW for ewmac_32_128
2025-12-08 21:27:32 DEBUG base_system {'stage': 'rules', 'instrument_code': 'RUSSELL'} Calculating raw forecast RUSSELL for ewmac_32_128
2025-12-08 21:27:32 DEBUG base_system {'stage': 'rules', 'instrument_code': 'SILVER'} Calculating raw forecast SILVER for ewmac_32_128
2025-12-08 21:27:33 DEBUG base_system {'stage': 'rules', 'instrument_code': 'SP500'} Calculating raw forecast SP500 for ewmac_32_128
2025-12-08 21:27:33 DEBUG base_system {'stage': 'rules', 'instrument_code': 'US10'} Calculating raw forecast US10 for ewmac_32_128
2025-12-08 21:27:33 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128
Loaded in: 4.2980568000348285

                 raw    scalar     scaled     capped
index
2024-03-15  5.975783  3.345292  19.990738  19.990738
2024-03-18  5.932453  3.345274  19.845684  19.845684
2024-03-19  6.049077  3.345254  20.235700  20.000000
2024-03-20  5.847705  3.345247  19.562016  19.562016
2024-03-21  6.042689  3.345231  20.214195  20.000000
2024-03-22  6.218251  3.345225  20.801451  20.000000
2024-03-25  6.373547  3.345212  21.320863  20.000000
2024-03-26  6.489081  3.345190  21.707212  20.000000
2024-03-27  6.655521  3.345177  22.263895  20.000000
2024-03-28  6.777110  3.345149  22.670443  20.000000

In [ ]:
# Forecast weights (fixed)
# https://github.com/robcarver17/pysystemtrade/blob/develop/docs/backtesting.md#forecast-weights-fixed

def test_forecast_combination_fixed():
    config = Config()
    config.instruments = portfolio_intruments
    config.use_forecast_weight_estimates=False
    #config.forecast_weights=dict(ewmac_20_60=0.5, ewmac_32_128=0.5)
    
    data = csvFuturesSimData()
    scale_and_cap = ForecastScaleCap()
    combine= ForecastCombine()
    system = System([scale_and_cap, combine, system_rules], data, config)

    capped_forecasts_1 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_5_20")
    capped_forecasts_2 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_20_60")
    capped_forecasts_3 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_32_128")
    capped_forecasts_4 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_60_150")
    capped_forecasts_5 = scale_and_cap.get_capped_forecast(test_instrument_code, "ewmac_100_200")
    combined_forecasts = combine.get_raw_combined_forecast_before_mapping(test_instrument_code)

    return pd.DataFrame({
        'ewmac_5_20': capped_forecasts_1,
        'ewmac_20_60': capped_forecasts_2,
        'ewmac_32_128': capped_forecasts_3,
        'ewmac_60_150': capped_forecasts_4,
        'ewmac_100_200': capped_forecasts_5,
        'combined (weighted)': combined_forecasts
    })

start = time.perf_counter()
df_pooling = test_forecast_combination_fixed().tail(10)
elapsed = time.perf_counter() - start
print(f"Loaded in: {elapsed}")
df_pooling

Private configuration private/private_config.yaml does not exist; no problem if running in sim mode
2025-12-08 21:27:34 DEBUG base_system Following instruments are 'duplicate_markets' ['Another_thing', 'bad_thing']
2025-12-08 21:27:34 DEBUG base_system Following instruments are marked as 'ignore_instruments': not included: ['EXAMPLE']
2025-12-08 21:27:34 DEBUG base_system Following instruments removed entirely from sim: ['Another_thing', 'EXAMPLE', 'bad_thing']
2025-12-08 21:27:34 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_32_128
2025-12-08 21:27:34 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_32_128
2025-12-08 21:27:34 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_100_200
2025-12-08 21:27:34 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_100_200
2025-12-08 21:27:34 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_20_60
2025-12-08 21:27:34 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_20_60
2025-12-08 21:27:35 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_5_20
2025-12-08 21:27:35 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_5_20
2025-12-08 21:27:35 DEBUG base_system {'stage': 'forecastScaleCap', 'instrument_code': 'NASDAQ'} Calculating capped forecast for NASDAQ ewmac_60_150
2025-12-08 21:27:35 DEBUG base_system {'stage': 'rules', 'instrument_code': 'NASDAQ'} Calculating raw forecast NASDAQ for ewmac_60_150
2025-12-08 21:27:35 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Calculating forecast weights for NASDAQ
2025-12-08 21:27:35 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} WARNING: No forecast weights  - using equal weights of 0.200 over all 5 trading rules in system
2025-12-08 21:27:35 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_100_200. Using costs of zero
2025-12-08 21:27:35 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_20_60. Using costs of zero
2025-12-08 21:27:35 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_32_128. Using costs of zero
2025-12-08 21:27:35 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_5_20. Using costs of zero
2025-12-08 21:27:35 WARNING base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} You need an accounts stage in the system to estimate forecast costs for NASDAQ ewmac_60_150. Using costs of zero
2025-12-08 21:27:35 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Only this set of rules ['ewmac_100_200', 'ewmac_20_60', 'ewmac_32_128', 'ewmac_5_20', 'ewmac_60_150'] is cheap enough to trade for NASDAQ
2025-12-08 21:27:35 DEBUG base_system {'stage': 'combForecast', 'instrument_code': 'NASDAQ'} Using fixed FDM multiplier of 1.000 for NASDAQ
Loaded in: 2.006594199920073

                 raw  scalar    scaled    capped  combined (weighted)
index
2024-03-15  5.975783     1.0  5.975783  5.975783             3.692515
2024-03-18  5.932453     1.0  5.932453  5.932453             3.667777
2024-03-19  6.049077     1.0  6.049077  6.049077             3.757104
2024-03-20  5.847705     1.0  5.847705  5.847705             3.717771
2024-03-21  6.042689     1.0  6.042689  6.042689             3.904592
2024-03-22  6.218251     1.0  6.218251  6.218251             4.049666
2024-03-25  6.373547     1.0  6.373547  6.373547             4.158222
2024-03-26  6.489081     1.0  6.489081  6.489081             4.219231
2024-03-27  6.655521     1.0  6.655521  6.655521             4.323969
2024-03-28  6.777110     1.0  6.777110  6.777110             4.386232